//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.14 at 07:28:29 PM IST 
//


package com.photon.phresco.plugins.model;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.photon.jaxb.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.photon.jaxb.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Mojos.Mojo.Configuration }
     * 
     */
    public Mojos.Mojo.Configuration createMojosMojoConfiguration() {
        return new Mojos.Mojo.Configuration();
    }

    /**
     * Create an instance of {@link Mojos.Mojo.Configuration.Parameters.Parameter.PossibleValues }
     * 
     */
    public Mojos.Mojo.Configuration.Parameters.Parameter.PossibleValues createMojosMojoConfigurationParametersParameterPossibleValues() {
        return new Mojos.Mojo.Configuration.Parameters.Parameter.PossibleValues();
    }

    /**
     * Create an instance of {@link Mojos.Mojo }
     * 
     */
    public Mojos.Mojo createMojosMojo() {
        return new Mojos.Mojo();
    }

    /**
     * Create an instance of {@link Mojos }
     * 
     */
    public Mojos createMojos() {
        return new Mojos();
    }

    /**
     * Create an instance of {@link Mojos.Mojo.Configuration.Parameters }
     * 
     */
    public Mojos.Mojo.Configuration.Parameters createMojosMojoConfigurationParameters() {
        return new Mojos.Mojo.Configuration.Parameters();
    }

    /**
     * Create an instance of {@link Mojos.Mojo.Configuration.Parameters.Parameter }
     * 
     */
    public Mojos.Mojo.Configuration.Parameters.Parameter createMojosMojoConfigurationParametersParameter() {
        return new Mojos.Mojo.Configuration.Parameters.Parameter();
    }

}
