//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.12.05 at 12:27:19 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://maven.apache.org/plugins/maven-assembly-plugin/assembly/1.1.0", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.photon.phresco.plugins.params.model;
