//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.15 at 07:26:46 PM IST 
//


package com.photon.phresco.plugins.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="mojo" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="goal" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="requiresDirectInvocation" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="requiresProject" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="requiresReports" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="aggregator" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="requiresOnline" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="inheritedByDefault" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="implementation" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="language" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="instantiationStrategy" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="executionStrategy" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="threadSafe" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="configuration">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="parameters">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="parameter" maxOccurs="unbounded" minOccurs="0">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="name">
 *                                                   &lt;complexType>
 *                                                     &lt;complexContent>
 *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                                         &lt;sequence>
 *                                                           &lt;element name="value" maxOccurs="unbounded" minOccurs="0">
 *                                                             &lt;complexType>
 *                                                               &lt;simpleContent>
 *                                                                 &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                                                                   &lt;attribute name="lang" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                                                 &lt;/extension>
 *                                                               &lt;/simpleContent>
 *                                                             &lt;/complexType>
 *                                                           &lt;/element>
 *                                                         &lt;/sequence>
 *                                                       &lt;/restriction>
 *                                                     &lt;/complexContent>
 *                                                   &lt;/complexType>
 *                                                 &lt;/element>
 *                                                 &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="dynamicParam" minOccurs="0">
 *                                                   &lt;complexType>
 *                                                     &lt;complexContent>
 *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                                         &lt;sequence>
 *                                                           &lt;element name="class" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                           &lt;element name="dependencies" maxOccurs="unbounded">
 *                                                             &lt;complexType>
 *                                                               &lt;complexContent>
 *                                                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                                                   &lt;sequence>
 *                                                                     &lt;element name="dependency">
 *                                                                       &lt;complexType>
 *                                                                         &lt;complexContent>
 *                                                                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                                                             &lt;sequence>
 *                                                                               &lt;element name="groupId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                                               &lt;element name="artifactId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                                               &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                                               &lt;element name="version" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                                             &lt;/sequence>
 *                                                                           &lt;/restriction>
 *                                                                         &lt;/complexContent>
 *                                                                       &lt;/complexType>
 *                                                                     &lt;/element>
 *                                                                   &lt;/sequence>
 *                                                                 &lt;/restriction>
 *                                                               &lt;/complexContent>
 *                                                             &lt;/complexType>
 *                                                           &lt;/element>
 *                                                         &lt;/sequence>
 *                                                       &lt;/restriction>
 *                                                     &lt;/complexContent>
 *                                                   &lt;/complexType>
 *                                                 &lt;/element>
 *                                                 &lt;element name="required" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="editable" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="key" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="possiblevalues" minOccurs="0">
 *                                                   &lt;complexType>
 *                                                     &lt;complexContent>
 *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                                         &lt;sequence>
 *                                                           &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *                                                         &lt;/sequence>
 *                                                       &lt;/restriction>
 *                                                     &lt;/complexContent>
 *                                                   &lt;/complexType>
 *                                                 &lt;/element>
 *                                                 &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "mojo"
})
@XmlRootElement(name = "mojos")
public class Mojos {

    protected List<Mojos.Mojo> mojo;

    /**
     * Gets the value of the mojo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the mojo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMojo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Mojos.Mojo }
     * 
     * 
     */
    public List<Mojos.Mojo> getMojo() {
        if (mojo == null) {
            mojo = new ArrayList<Mojos.Mojo>();
        }
        return this.mojo;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="goal" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="requiresDirectInvocation" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="requiresProject" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="requiresReports" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="aggregator" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="requiresOnline" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="inheritedByDefault" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="implementation" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="language" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="instantiationStrategy" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="executionStrategy" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="threadSafe" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="configuration">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="parameters">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="parameter" maxOccurs="unbounded" minOccurs="0">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="name">
     *                                         &lt;complexType>
     *                                           &lt;complexContent>
     *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                               &lt;sequence>
     *                                                 &lt;element name="value" maxOccurs="unbounded" minOccurs="0">
     *                                                   &lt;complexType>
     *                                                     &lt;simpleContent>
     *                                                       &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                                                         &lt;attribute name="lang" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                                                       &lt;/extension>
     *                                                     &lt;/simpleContent>
     *                                                   &lt;/complexType>
     *                                                 &lt;/element>
     *                                               &lt;/sequence>
     *                                             &lt;/restriction>
     *                                           &lt;/complexContent>
     *                                         &lt;/complexType>
     *                                       &lt;/element>
     *                                       &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                       &lt;element name="dynamicParam" minOccurs="0">
     *                                         &lt;complexType>
     *                                           &lt;complexContent>
     *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                               &lt;sequence>
     *                                                 &lt;element name="class" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                                 &lt;element name="dependencies" maxOccurs="unbounded">
     *                                                   &lt;complexType>
     *                                                     &lt;complexContent>
     *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                                         &lt;sequence>
     *                                                           &lt;element name="dependency">
     *                                                             &lt;complexType>
     *                                                               &lt;complexContent>
     *                                                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                                                   &lt;sequence>
     *                                                                     &lt;element name="groupId" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                                                     &lt;element name="artifactId" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                                                     &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                                                     &lt;element name="version" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                                                   &lt;/sequence>
     *                                                                 &lt;/restriction>
     *                                                               &lt;/complexContent>
     *                                                             &lt;/complexType>
     *                                                           &lt;/element>
     *                                                         &lt;/sequence>
     *                                                       &lt;/restriction>
     *                                                     &lt;/complexContent>
     *                                                   &lt;/complexType>
     *                                                 &lt;/element>
     *                                               &lt;/sequence>
     *                                             &lt;/restriction>
     *                                           &lt;/complexContent>
     *                                         &lt;/complexType>
     *                                       &lt;/element>
     *                                       &lt;element name="required" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                       &lt;element name="editable" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                       &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                       &lt;element name="key" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                       &lt;element name="possiblevalues" minOccurs="0">
     *                                         &lt;complexType>
     *                                           &lt;complexContent>
     *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                               &lt;sequence>
     *                                                 &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
     *                                               &lt;/sequence>
     *                                             &lt;/restriction>
     *                                           &lt;/complexContent>
     *                                         &lt;/complexType>
     *                                       &lt;/element>
     *                                       &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                     &lt;/sequence>
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "goal",
        "description",
        "requiresDirectInvocation",
        "requiresProject",
        "requiresReports",
        "aggregator",
        "requiresOnline",
        "inheritedByDefault",
        "implementation",
        "language",
        "instantiationStrategy",
        "executionStrategy",
        "threadSafe",
        "configuration"
    })
    public static class Mojo {

        @XmlElement(required = true)
        protected String goal;
        @XmlElement(required = true)
        protected String description;
        @XmlElement(required = true)
        protected String requiresDirectInvocation;
        @XmlElement(required = true)
        protected String requiresProject;
        @XmlElement(required = true)
        protected String requiresReports;
        @XmlElement(required = true)
        protected String aggregator;
        @XmlElement(required = true)
        protected String requiresOnline;
        @XmlElement(required = true)
        protected String inheritedByDefault;
        @XmlElement(required = true)
        protected String implementation;
        @XmlElement(required = true)
        protected String language;
        @XmlElement(required = true)
        protected String instantiationStrategy;
        @XmlElement(required = true)
        protected String executionStrategy;
        @XmlElement(required = true)
        protected String threadSafe;
        @XmlElement(required = true)
        protected Mojos.Mojo.Configuration configuration;

        /**
         * Gets the value of the goal property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getGoal() {
            return goal;
        }

        /**
         * Sets the value of the goal property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setGoal(String value) {
            this.goal = value;
        }

        /**
         * Gets the value of the description property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDescription() {
            return description;
        }

        /**
         * Sets the value of the description property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDescription(String value) {
            this.description = value;
        }

        /**
         * Gets the value of the requiresDirectInvocation property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRequiresDirectInvocation() {
            return requiresDirectInvocation;
        }

        /**
         * Sets the value of the requiresDirectInvocation property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRequiresDirectInvocation(String value) {
            this.requiresDirectInvocation = value;
        }

        /**
         * Gets the value of the requiresProject property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRequiresProject() {
            return requiresProject;
        }

        /**
         * Sets the value of the requiresProject property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRequiresProject(String value) {
            this.requiresProject = value;
        }

        /**
         * Gets the value of the requiresReports property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRequiresReports() {
            return requiresReports;
        }

        /**
         * Sets the value of the requiresReports property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRequiresReports(String value) {
            this.requiresReports = value;
        }

        /**
         * Gets the value of the aggregator property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAggregator() {
            return aggregator;
        }

        /**
         * Sets the value of the aggregator property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAggregator(String value) {
            this.aggregator = value;
        }

        /**
         * Gets the value of the requiresOnline property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRequiresOnline() {
            return requiresOnline;
        }

        /**
         * Sets the value of the requiresOnline property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRequiresOnline(String value) {
            this.requiresOnline = value;
        }

        /**
         * Gets the value of the inheritedByDefault property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getInheritedByDefault() {
            return inheritedByDefault;
        }

        /**
         * Sets the value of the inheritedByDefault property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setInheritedByDefault(String value) {
            this.inheritedByDefault = value;
        }

        /**
         * Gets the value of the implementation property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getImplementation() {
            return implementation;
        }

        /**
         * Sets the value of the implementation property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setImplementation(String value) {
            this.implementation = value;
        }

        /**
         * Gets the value of the language property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLanguage() {
            return language;
        }

        /**
         * Sets the value of the language property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLanguage(String value) {
            this.language = value;
        }

        /**
         * Gets the value of the instantiationStrategy property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getInstantiationStrategy() {
            return instantiationStrategy;
        }

        /**
         * Sets the value of the instantiationStrategy property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setInstantiationStrategy(String value) {
            this.instantiationStrategy = value;
        }

        /**
         * Gets the value of the executionStrategy property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getExecutionStrategy() {
            return executionStrategy;
        }

        /**
         * Sets the value of the executionStrategy property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setExecutionStrategy(String value) {
            this.executionStrategy = value;
        }

        /**
         * Gets the value of the threadSafe property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getThreadSafe() {
            return threadSafe;
        }

        /**
         * Sets the value of the threadSafe property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setThreadSafe(String value) {
            this.threadSafe = value;
        }

        /**
         * Gets the value of the configuration property.
         * 
         * @return
         *     possible object is
         *     {@link Mojos.Mojo.Configuration }
         *     
         */
        public Mojos.Mojo.Configuration getConfiguration() {
            return configuration;
        }

        /**
         * Sets the value of the configuration property.
         * 
         * @param value
         *     allowed object is
         *     {@link Mojos.Mojo.Configuration }
         *     
         */
        public void setConfiguration(Mojos.Mojo.Configuration value) {
            this.configuration = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="parameters">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="parameter" maxOccurs="unbounded" minOccurs="0">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="name">
         *                               &lt;complexType>
         *                                 &lt;complexContent>
         *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                                     &lt;sequence>
         *                                       &lt;element name="value" maxOccurs="unbounded" minOccurs="0">
         *                                         &lt;complexType>
         *                                           &lt;simpleContent>
         *                                             &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *                                               &lt;attribute name="lang" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                                             &lt;/extension>
         *                                           &lt;/simpleContent>
         *                                         &lt;/complexType>
         *                                       &lt;/element>
         *                                     &lt;/sequence>
         *                                   &lt;/restriction>
         *                                 &lt;/complexContent>
         *                               &lt;/complexType>
         *                             &lt;/element>
         *                             &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                             &lt;element name="dynamicParam" minOccurs="0">
         *                               &lt;complexType>
         *                                 &lt;complexContent>
         *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                                     &lt;sequence>
         *                                       &lt;element name="class" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                                       &lt;element name="dependencies" maxOccurs="unbounded">
         *                                         &lt;complexType>
         *                                           &lt;complexContent>
         *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                                               &lt;sequence>
         *                                                 &lt;element name="dependency">
         *                                                   &lt;complexType>
         *                                                     &lt;complexContent>
         *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                                                         &lt;sequence>
         *                                                           &lt;element name="groupId" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                                                           &lt;element name="artifactId" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                                                           &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                                                           &lt;element name="version" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                                                         &lt;/sequence>
         *                                                       &lt;/restriction>
         *                                                     &lt;/complexContent>
         *                                                   &lt;/complexType>
         *                                                 &lt;/element>
         *                                               &lt;/sequence>
         *                                             &lt;/restriction>
         *                                           &lt;/complexContent>
         *                                         &lt;/complexType>
         *                                       &lt;/element>
         *                                     &lt;/sequence>
         *                                   &lt;/restriction>
         *                                 &lt;/complexContent>
         *                               &lt;/complexType>
         *                             &lt;/element>
         *                             &lt;element name="required" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                             &lt;element name="editable" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                             &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                             &lt;element name="key" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                             &lt;element name="possiblevalues" minOccurs="0">
         *                               &lt;complexType>
         *                                 &lt;complexContent>
         *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                                     &lt;sequence>
         *                                       &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
         *                                     &lt;/sequence>
         *                                   &lt;/restriction>
         *                                 &lt;/complexContent>
         *                               &lt;/complexType>
         *                             &lt;/element>
         *                             &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                           &lt;/sequence>
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "parameters"
        })
        public static class Configuration {

            @XmlElement(required = true)
            protected Mojos.Mojo.Configuration.Parameters parameters;

            /**
             * Gets the value of the parameters property.
             * 
             * @return
             *     possible object is
             *     {@link Mojos.Mojo.Configuration.Parameters }
             *     
             */
            public Mojos.Mojo.Configuration.Parameters getParameters() {
                return parameters;
            }

            /**
             * Sets the value of the parameters property.
             * 
             * @param value
             *     allowed object is
             *     {@link Mojos.Mojo.Configuration.Parameters }
             *     
             */
            public void setParameters(Mojos.Mojo.Configuration.Parameters value) {
                this.parameters = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="parameter" maxOccurs="unbounded" minOccurs="0">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="name">
             *                     &lt;complexType>
             *                       &lt;complexContent>
             *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                           &lt;sequence>
             *                             &lt;element name="value" maxOccurs="unbounded" minOccurs="0">
             *                               &lt;complexType>
             *                                 &lt;simpleContent>
             *                                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
             *                                     &lt;attribute name="lang" type="{http://www.w3.org/2001/XMLSchema}string" />
             *                                   &lt;/extension>
             *                                 &lt;/simpleContent>
             *                               &lt;/complexType>
             *                             &lt;/element>
             *                           &lt;/sequence>
             *                         &lt;/restriction>
             *                       &lt;/complexContent>
             *                     &lt;/complexType>
             *                   &lt;/element>
             *                   &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                   &lt;element name="dynamicParam" minOccurs="0">
             *                     &lt;complexType>
             *                       &lt;complexContent>
             *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                           &lt;sequence>
             *                             &lt;element name="class" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                             &lt;element name="dependencies" maxOccurs="unbounded">
             *                               &lt;complexType>
             *                                 &lt;complexContent>
             *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                                     &lt;sequence>
             *                                       &lt;element name="dependency">
             *                                         &lt;complexType>
             *                                           &lt;complexContent>
             *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                                               &lt;sequence>
             *                                                 &lt;element name="groupId" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                                                 &lt;element name="artifactId" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                                                 &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                                                 &lt;element name="version" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                                               &lt;/sequence>
             *                                             &lt;/restriction>
             *                                           &lt;/complexContent>
             *                                         &lt;/complexType>
             *                                       &lt;/element>
             *                                     &lt;/sequence>
             *                                   &lt;/restriction>
             *                                 &lt;/complexContent>
             *                               &lt;/complexType>
             *                             &lt;/element>
             *                           &lt;/sequence>
             *                         &lt;/restriction>
             *                       &lt;/complexContent>
             *                     &lt;/complexType>
             *                   &lt;/element>
             *                   &lt;element name="required" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                   &lt;element name="editable" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                   &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                   &lt;element name="key" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                   &lt;element name="possiblevalues" minOccurs="0">
             *                     &lt;complexType>
             *                       &lt;complexContent>
             *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                           &lt;sequence>
             *                             &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
             *                           &lt;/sequence>
             *                         &lt;/restriction>
             *                       &lt;/complexContent>
             *                     &lt;/complexType>
             *                   &lt;/element>
             *                   &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                 &lt;/sequence>
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "parameter"
            })
            public static class Parameters {

                protected List<Mojos.Mojo.Configuration.Parameters.Parameter> parameter;

                /**
                 * Gets the value of the parameter property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the parameter property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getParameter().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link Mojos.Mojo.Configuration.Parameters.Parameter }
                 * 
                 * 
                 */
                public List<Mojos.Mojo.Configuration.Parameters.Parameter> getParameter() {
                    if (parameter == null) {
                        parameter = new ArrayList<Mojos.Mojo.Configuration.Parameters.Parameter>();
                    }
                    return this.parameter;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="name">
                 *           &lt;complexType>
                 *             &lt;complexContent>
                 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *                 &lt;sequence>
                 *                   &lt;element name="value" maxOccurs="unbounded" minOccurs="0">
                 *                     &lt;complexType>
                 *                       &lt;simpleContent>
                 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
                 *                           &lt;attribute name="lang" type="{http://www.w3.org/2001/XMLSchema}string" />
                 *                         &lt;/extension>
                 *                       &lt;/simpleContent>
                 *                     &lt;/complexType>
                 *                   &lt;/element>
                 *                 &lt;/sequence>
                 *               &lt;/restriction>
                 *             &lt;/complexContent>
                 *           &lt;/complexType>
                 *         &lt;/element>
                 *         &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *         &lt;element name="dynamicParam" minOccurs="0">
                 *           &lt;complexType>
                 *             &lt;complexContent>
                 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *                 &lt;sequence>
                 *                   &lt;element name="class" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *                   &lt;element name="dependencies" maxOccurs="unbounded">
                 *                     &lt;complexType>
                 *                       &lt;complexContent>
                 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *                           &lt;sequence>
                 *                             &lt;element name="dependency">
                 *                               &lt;complexType>
                 *                                 &lt;complexContent>
                 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *                                     &lt;sequence>
                 *                                       &lt;element name="groupId" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *                                       &lt;element name="artifactId" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *                                       &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *                                       &lt;element name="version" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *                                     &lt;/sequence>
                 *                                   &lt;/restriction>
                 *                                 &lt;/complexContent>
                 *                               &lt;/complexType>
                 *                             &lt;/element>
                 *                           &lt;/sequence>
                 *                         &lt;/restriction>
                 *                       &lt;/complexContent>
                 *                     &lt;/complexType>
                 *                   &lt;/element>
                 *                 &lt;/sequence>
                 *               &lt;/restriction>
                 *             &lt;/complexContent>
                 *           &lt;/complexType>
                 *         &lt;/element>
                 *         &lt;element name="required" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *         &lt;element name="editable" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *         &lt;element name="key" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *         &lt;element name="possiblevalues" minOccurs="0">
                 *           &lt;complexType>
                 *             &lt;complexContent>
                 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *                 &lt;sequence>
                 *                   &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
                 *                 &lt;/sequence>
                 *               &lt;/restriction>
                 *             &lt;/complexContent>
                 *           &lt;/complexType>
                 *         &lt;/element>
                 *         &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *       &lt;/sequence>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "name",
                    "type",
                    "dynamicParam",
                    "required",
                    "editable",
                    "description",
                    "key",
                    "possiblevalues",
                    "value"
                })
                public static class Parameter {

                    @XmlElement(required = true)
                    protected Mojos.Mojo.Configuration.Parameters.Parameter.Name name;
                    @XmlElement(required = true)
                    protected String type;
                    protected Mojos.Mojo.Configuration.Parameters.Parameter.DynamicParam dynamicParam;
                    @XmlElement(required = true)
                    protected String required;
                    @XmlElement(required = true)
                    protected String editable;
                    @XmlElement(required = true)
                    protected String description;
                    @XmlElement(required = true)
                    protected String key;
                    protected Mojos.Mojo.Configuration.Parameters.Parameter.Possiblevalues possiblevalues;
                    @XmlElement(required = true)
                    protected String value;

                    /**
                     * Gets the value of the name property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link Mojos.Mojo.Configuration.Parameters.Parameter.Name }
                     *     
                     */
                    public Mojos.Mojo.Configuration.Parameters.Parameter.Name getName() {
                        return name;
                    }

                    /**
                     * Sets the value of the name property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link Mojos.Mojo.Configuration.Parameters.Parameter.Name }
                     *     
                     */
                    public void setName(Mojos.Mojo.Configuration.Parameters.Parameter.Name value) {
                        this.name = value;
                    }

                    /**
                     * Gets the value of the type property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getType() {
                        return type;
                    }

                    /**
                     * Sets the value of the type property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setType(String value) {
                        this.type = value;
                    }

                    /**
                     * Gets the value of the dynamicParam property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link Mojos.Mojo.Configuration.Parameters.Parameter.DynamicParam }
                     *     
                     */
                    public Mojos.Mojo.Configuration.Parameters.Parameter.DynamicParam getDynamicParam() {
                        return dynamicParam;
                    }

                    /**
                     * Sets the value of the dynamicParam property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link Mojos.Mojo.Configuration.Parameters.Parameter.DynamicParam }
                     *     
                     */
                    public void setDynamicParam(Mojos.Mojo.Configuration.Parameters.Parameter.DynamicParam value) {
                        this.dynamicParam = value;
                    }

                    /**
                     * Gets the value of the required property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getRequired() {
                        return required;
                    }

                    /**
                     * Sets the value of the required property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setRequired(String value) {
                        this.required = value;
                    }

                    /**
                     * Gets the value of the editable property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getEditable() {
                        return editable;
                    }

                    /**
                     * Sets the value of the editable property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setEditable(String value) {
                        this.editable = value;
                    }

                    /**
                     * Gets the value of the description property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getDescription() {
                        return description;
                    }

                    /**
                     * Sets the value of the description property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setDescription(String value) {
                        this.description = value;
                    }

                    /**
                     * Gets the value of the key property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getKey() {
                        return key;
                    }

                    /**
                     * Sets the value of the key property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setKey(String value) {
                        this.key = value;
                    }

                    /**
                     * Gets the value of the possiblevalues property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link Mojos.Mojo.Configuration.Parameters.Parameter.Possiblevalues }
                     *     
                     */
                    public Mojos.Mojo.Configuration.Parameters.Parameter.Possiblevalues getPossiblevalues() {
                        return possiblevalues;
                    }

                    /**
                     * Sets the value of the possiblevalues property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link Mojos.Mojo.Configuration.Parameters.Parameter.Possiblevalues }
                     *     
                     */
                    public void setPossiblevalues(Mojos.Mojo.Configuration.Parameters.Parameter.Possiblevalues value) {
                        this.possiblevalues = value;
                    }

                    /**
                     * Gets the value of the value property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getValue() {
                        return value;
                    }

                    /**
                     * Sets the value of the value property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setValue(String value) {
                        this.value = value;
                    }


                    /**
                     * <p>Java class for anonymous complex type.
                     * 
                     * <p>The following schema fragment specifies the expected content contained within this class.
                     * 
                     * <pre>
                     * &lt;complexType>
                     *   &lt;complexContent>
                     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                     *       &lt;sequence>
                     *         &lt;element name="class" type="{http://www.w3.org/2001/XMLSchema}string"/>
                     *         &lt;element name="dependencies" maxOccurs="unbounded">
                     *           &lt;complexType>
                     *             &lt;complexContent>
                     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                     *                 &lt;sequence>
                     *                   &lt;element name="dependency">
                     *                     &lt;complexType>
                     *                       &lt;complexContent>
                     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                     *                           &lt;sequence>
                     *                             &lt;element name="groupId" type="{http://www.w3.org/2001/XMLSchema}string"/>
                     *                             &lt;element name="artifactId" type="{http://www.w3.org/2001/XMLSchema}string"/>
                     *                             &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
                     *                             &lt;element name="version" type="{http://www.w3.org/2001/XMLSchema}string"/>
                     *                           &lt;/sequence>
                     *                         &lt;/restriction>
                     *                       &lt;/complexContent>
                     *                     &lt;/complexType>
                     *                   &lt;/element>
                     *                 &lt;/sequence>
                     *               &lt;/restriction>
                     *             &lt;/complexContent>
                     *           &lt;/complexType>
                     *         &lt;/element>
                     *       &lt;/sequence>
                     *     &lt;/restriction>
                     *   &lt;/complexContent>
                     * &lt;/complexType>
                     * </pre>
                     * 
                     * 
                     */
                    @XmlAccessorType(XmlAccessType.FIELD)
                    @XmlType(name = "", propOrder = {
                        "clazz",
                        "dependencies"
                    })
                    public static class DynamicParam {

                        @XmlElement(name = "class", required = true)
                        protected String clazz;
                        @XmlElement(required = true)
                        protected List<Mojos.Mojo.Configuration.Parameters.Parameter.DynamicParam.Dependencies> dependencies;

                        /**
                         * Gets the value of the clazz property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public String getClazz() {
                            return clazz;
                        }

                        /**
                         * Sets the value of the clazz property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setClazz(String value) {
                            this.clazz = value;
                        }

                        /**
                         * Gets the value of the dependencies property.
                         * 
                         * <p>
                         * This accessor method returns a reference to the live list,
                         * not a snapshot. Therefore any modification you make to the
                         * returned list will be present inside the JAXB object.
                         * This is why there is not a <CODE>set</CODE> method for the dependencies property.
                         * 
                         * <p>
                         * For example, to add a new item, do as follows:
                         * <pre>
                         *    getDependencies().add(newItem);
                         * </pre>
                         * 
                         * 
                         * <p>
                         * Objects of the following type(s) are allowed in the list
                         * {@link Mojos.Mojo.Configuration.Parameters.Parameter.DynamicParam.Dependencies }
                         * 
                         * 
                         */
                        public List<Mojos.Mojo.Configuration.Parameters.Parameter.DynamicParam.Dependencies> getDependencies() {
                            if (dependencies == null) {
                                dependencies = new ArrayList<Mojos.Mojo.Configuration.Parameters.Parameter.DynamicParam.Dependencies>();
                            }
                            return this.dependencies;
                        }


                        /**
                         * <p>Java class for anonymous complex type.
                         * 
                         * <p>The following schema fragment specifies the expected content contained within this class.
                         * 
                         * <pre>
                         * &lt;complexType>
                         *   &lt;complexContent>
                         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                         *       &lt;sequence>
                         *         &lt;element name="dependency">
                         *           &lt;complexType>
                         *             &lt;complexContent>
                         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                         *                 &lt;sequence>
                         *                   &lt;element name="groupId" type="{http://www.w3.org/2001/XMLSchema}string"/>
                         *                   &lt;element name="artifactId" type="{http://www.w3.org/2001/XMLSchema}string"/>
                         *                   &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
                         *                   &lt;element name="version" type="{http://www.w3.org/2001/XMLSchema}string"/>
                         *                 &lt;/sequence>
                         *               &lt;/restriction>
                         *             &lt;/complexContent>
                         *           &lt;/complexType>
                         *         &lt;/element>
                         *       &lt;/sequence>
                         *     &lt;/restriction>
                         *   &lt;/complexContent>
                         * &lt;/complexType>
                         * </pre>
                         * 
                         * 
                         */
                        @XmlAccessorType(XmlAccessType.FIELD)
                        @XmlType(name = "", propOrder = {
                            "dependency"
                        })
                        public static class Dependencies {

                            @XmlElement(required = true)
                            protected Mojos.Mojo.Configuration.Parameters.Parameter.DynamicParam.Dependencies.Dependency dependency;

                            /**
                             * Gets the value of the dependency property.
                             * 
                             * @return
                             *     possible object is
                             *     {@link Mojos.Mojo.Configuration.Parameters.Parameter.DynamicParam.Dependencies.Dependency }
                             *     
                             */
                            public Mojos.Mojo.Configuration.Parameters.Parameter.DynamicParam.Dependencies.Dependency getDependency() {
                                return dependency;
                            }

                            /**
                             * Sets the value of the dependency property.
                             * 
                             * @param value
                             *     allowed object is
                             *     {@link Mojos.Mojo.Configuration.Parameters.Parameter.DynamicParam.Dependencies.Dependency }
                             *     
                             */
                            public void setDependency(Mojos.Mojo.Configuration.Parameters.Parameter.DynamicParam.Dependencies.Dependency value) {
                                this.dependency = value;
                            }


                            /**
                             * <p>Java class for anonymous complex type.
                             * 
                             * <p>The following schema fragment specifies the expected content contained within this class.
                             * 
                             * <pre>
                             * &lt;complexType>
                             *   &lt;complexContent>
                             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                             *       &lt;sequence>
                             *         &lt;element name="groupId" type="{http://www.w3.org/2001/XMLSchema}string"/>
                             *         &lt;element name="artifactId" type="{http://www.w3.org/2001/XMLSchema}string"/>
                             *         &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
                             *         &lt;element name="version" type="{http://www.w3.org/2001/XMLSchema}string"/>
                             *       &lt;/sequence>
                             *     &lt;/restriction>
                             *   &lt;/complexContent>
                             * &lt;/complexType>
                             * </pre>
                             * 
                             * 
                             */
                            @XmlAccessorType(XmlAccessType.FIELD)
                            @XmlType(name = "", propOrder = {
                                "groupId",
                                "artifactId",
                                "type",
                                "version"
                            })
                            public static class Dependency {

                                @XmlElement(required = true)
                                protected String groupId;
                                @XmlElement(required = true)
                                protected String artifactId;
                                @XmlElement(required = true)
                                protected String type;
                                @XmlElement(required = true)
                                protected String version;

                                /**
                                 * Gets the value of the groupId property.
                                 * 
                                 * @return
                                 *     possible object is
                                 *     {@link String }
                                 *     
                                 */
                                public String getGroupId() {
                                    return groupId;
                                }

                                /**
                                 * Sets the value of the groupId property.
                                 * 
                                 * @param value
                                 *     allowed object is
                                 *     {@link String }
                                 *     
                                 */
                                public void setGroupId(String value) {
                                    this.groupId = value;
                                }

                                /**
                                 * Gets the value of the artifactId property.
                                 * 
                                 * @return
                                 *     possible object is
                                 *     {@link String }
                                 *     
                                 */
                                public String getArtifactId() {
                                    return artifactId;
                                }

                                /**
                                 * Sets the value of the artifactId property.
                                 * 
                                 * @param value
                                 *     allowed object is
                                 *     {@link String }
                                 *     
                                 */
                                public void setArtifactId(String value) {
                                    this.artifactId = value;
                                }

                                /**
                                 * Gets the value of the type property.
                                 * 
                                 * @return
                                 *     possible object is
                                 *     {@link String }
                                 *     
                                 */
                                public String getType() {
                                    return type;
                                }

                                /**
                                 * Sets the value of the type property.
                                 * 
                                 * @param value
                                 *     allowed object is
                                 *     {@link String }
                                 *     
                                 */
                                public void setType(String value) {
                                    this.type = value;
                                }

                                /**
                                 * Gets the value of the version property.
                                 * 
                                 * @return
                                 *     possible object is
                                 *     {@link String }
                                 *     
                                 */
                                public String getVersion() {
                                    return version;
                                }

                                /**
                                 * Sets the value of the version property.
                                 * 
                                 * @param value
                                 *     allowed object is
                                 *     {@link String }
                                 *     
                                 */
                                public void setVersion(String value) {
                                    this.version = value;
                                }

                            }

                        }

                    }


                    /**
                     * <p>Java class for anonymous complex type.
                     * 
                     * <p>The following schema fragment specifies the expected content contained within this class.
                     * 
                     * <pre>
                     * &lt;complexType>
                     *   &lt;complexContent>
                     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                     *       &lt;sequence>
                     *         &lt;element name="value" maxOccurs="unbounded" minOccurs="0">
                     *           &lt;complexType>
                     *             &lt;simpleContent>
                     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
                     *                 &lt;attribute name="lang" type="{http://www.w3.org/2001/XMLSchema}string" />
                     *               &lt;/extension>
                     *             &lt;/simpleContent>
                     *           &lt;/complexType>
                     *         &lt;/element>
                     *       &lt;/sequence>
                     *     &lt;/restriction>
                     *   &lt;/complexContent>
                     * &lt;/complexType>
                     * </pre>
                     * 
                     * 
                     */
                    @XmlAccessorType(XmlAccessType.FIELD)
                    @XmlType(name = "", propOrder = {
                        "value"
                    })
                    public static class Name {

                        protected List<Mojos.Mojo.Configuration.Parameters.Parameter.Name.Value> value;

                        /**
                         * Gets the value of the value property.
                         * 
                         * <p>
                         * This accessor method returns a reference to the live list,
                         * not a snapshot. Therefore any modification you make to the
                         * returned list will be present inside the JAXB object.
                         * This is why there is not a <CODE>set</CODE> method for the value property.
                         * 
                         * <p>
                         * For example, to add a new item, do as follows:
                         * <pre>
                         *    getValue().add(newItem);
                         * </pre>
                         * 
                         * 
                         * <p>
                         * Objects of the following type(s) are allowed in the list
                         * {@link Mojos.Mojo.Configuration.Parameters.Parameter.Name.Value }
                         * 
                         * 
                         */
                        public List<Mojos.Mojo.Configuration.Parameters.Parameter.Name.Value> getValue() {
                            if (value == null) {
                                value = new ArrayList<Mojos.Mojo.Configuration.Parameters.Parameter.Name.Value>();
                            }
                            return this.value;
                        }


                        /**
                         * <p>Java class for anonymous complex type.
                         * 
                         * <p>The following schema fragment specifies the expected content contained within this class.
                         * 
                         * <pre>
                         * &lt;complexType>
                         *   &lt;simpleContent>
                         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
                         *       &lt;attribute name="lang" type="{http://www.w3.org/2001/XMLSchema}string" />
                         *     &lt;/extension>
                         *   &lt;/simpleContent>
                         * &lt;/complexType>
                         * </pre>
                         * 
                         * 
                         */
                        @XmlAccessorType(XmlAccessType.FIELD)
                        @XmlType(name = "", propOrder = {
                            "value"
                        })
                        public static class Value {

                            @XmlValue
                            protected String value;
                            @XmlAttribute(name = "lang")
                            protected String lang;

                            /**
                             * Gets the value of the value property.
                             * 
                             * @return
                             *     possible object is
                             *     {@link String }
                             *     
                             */
                            public String getValue() {
                                return value;
                            }

                            /**
                             * Sets the value of the value property.
                             * 
                             * @param value
                             *     allowed object is
                             *     {@link String }
                             *     
                             */
                            public void setValue(String value) {
                                this.value = value;
                            }

                            /**
                             * Gets the value of the lang property.
                             * 
                             * @return
                             *     possible object is
                             *     {@link String }
                             *     
                             */
                            public String getLang() {
                                return lang;
                            }

                            /**
                             * Sets the value of the lang property.
                             * 
                             * @param value
                             *     allowed object is
                             *     {@link String }
                             *     
                             */
                            public void setLang(String value) {
                                this.lang = value;
                            }

                        }

                    }


                    /**
                     * <p>Java class for anonymous complex type.
                     * 
                     * <p>The following schema fragment specifies the expected content contained within this class.
                     * 
                     * <pre>
                     * &lt;complexType>
                     *   &lt;complexContent>
                     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                     *       &lt;sequence>
                     *         &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
                     *       &lt;/sequence>
                     *     &lt;/restriction>
                     *   &lt;/complexContent>
                     * &lt;/complexType>
                     * </pre>
                     * 
                     * 
                     */
                    @XmlAccessorType(XmlAccessType.FIELD)
                    @XmlType(name = "", propOrder = {
                        "value"
                    })
                    public static class Possiblevalues {

                        protected List<String> value;

                        /**
                         * Gets the value of the value property.
                         * 
                         * <p>
                         * This accessor method returns a reference to the live list,
                         * not a snapshot. Therefore any modification you make to the
                         * returned list will be present inside the JAXB object.
                         * This is why there is not a <CODE>set</CODE> method for the value property.
                         * 
                         * <p>
                         * For example, to add a new item, do as follows:
                         * <pre>
                         *    getValue().add(newItem);
                         * </pre>
                         * 
                         * 
                         * <p>
                         * Objects of the following type(s) are allowed in the list
                         * {@link String }
                         * 
                         * 
                         */
                        public List<String> getValue() {
                            if (value == null) {
                                value = new ArrayList<String>();
                            }
                            return this.value;
                        }

                    }

                }

            }

        }

    }

}
